services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: camera-llm:latest
    container_name: camera-llm
    restart: unless-stopped
    environment:
      CAPTURE_INTERVAL_SEC: ${CAPTURE_INTERVAL_SEC:-10}
      CAMERA_INDEX: ${CAMERA_INDEX:-0}
      CAMERA_RTSP_URL: ${CAMERA_RTSP_URL:-}
      # Use LM Studio by default (override in .env or CLI as needed)
      ANSWER_MODE: ${ANSWER_MODE:-lmstudio}
      LMSTUDIO_BASE_URL: ${LMSTUDIO_BASE_URL:-http://host.docker.internal:1234}
      LMSTUDIO_MODEL: ${LMSTUDIO_MODEL:-openai/gpt-oss-20b}
      LMSTUDIO_API_KEY: ${LMSTUDIO_API_KEY:-}
      LMSTUDIO_MAX_TOKENS: ${LMSTUDIO_MAX_TOKENS:-}
      LMSTUDIO_TEMPERATURE: ${LMSTUDIO_TEMPERATURE:-0.2}
      LMSTUDIO_VISION_MODEL: ${LMSTUDIO_VISION_MODEL:-}
      LMSTUDIO_VISION_MAX_TOKENS: ${LMSTUDIO_VISION_MAX_TOKENS:-}
      LMSTUDIO_VISION_IMAGE_SIZE: ${LMSTUDIO_VISION_IMAGE_SIZE:-896}
      LMSTUDIO_VISION_PAD_COLOR: ${LMSTUDIO_VISION_PAD_COLOR:-#000000}
      LOCAL_LLM_KIND: ${LOCAL_LLM_KIND:-ollama}
      LOCAL_LLM_BASE_URL: ${LOCAL_LLM_BASE_URL:-http://ollama:11434}
      LOCAL_LLM_MODEL: ${LOCAL_LLM_MODEL:-qwen2.5:7b}
      VISION_MODE: ${VISION_MODE:-lmstudio}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://ollama:11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-llava:7b}
      WEBHOOK_URL: ${WEBHOOK_URL:-http://webhook:80/inbox}
      WEBHOOK_QUEUE_FILE: ${WEBHOOK_QUEUE_FILE:-/data/webhook_queue.jsonl}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
      BROWSER_MODE: ${BROWSER_MODE:-false}
      BROWSER_USER_DATA_DIR: ${BROWSER_USER_DATA_DIR:-/data/playwright}
    ports:
      - "8000:8000"
    volumes:
      - appdata:/data
    depends_on:
      - ollama
      - webhook

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  webhook:
    image: ealen/echo-server:latest
    container_name: webhook
    restart: unless-stopped
    ports:
      - "9000:80"

volumes:
  appdata:
  ollama:
